services:
  api:
    build:
      context: ..
      dockerfile: app/Dockerfile
    container_name: netscanner-api
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    environment:
      POSTGRES_DSN: postgresql+asyncpg://netscanner:netscanner@db:5432/netscanner
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - app-network

  migrations:
    build:
      context: ..
      dockerfile: app/Dockerfile
    container_name: netscanner-migrations
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_DSN: postgresql+asyncpg://netscanner:netscanner@db:5432/netscanner
    command: ["alembic", "upgrade", "head"]
    restart: "no"
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    container_name: netscanner-db
    environment:
      POSTGRES_DB: netscanner
      POSTGRES_USER: netscanner
      POSTGRES_PASSWORD: netscanner
    restart: unless-stopped
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d netscanner -U netscanner"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
